### ISSUE TITLE
Fubarino Mini Minimal Sketch using DSPI fails to compile

### ISSUE THREAD

**Issue by ricklon** [chipKIT32/chipKIT-core#189]
```
#include <DSPI.h>

DSPI0 spi;

void setup() {
  spi.begin();
  spi.setSpeed(250000);
  spi.enableInterruptTransfer();
}
void loop() {
}
```

error:
```
/Users/rickanderson/Library/Arduino15/packages/chipKIT/hardware/pic32/1.1.0/libraries/DSPI/DSPI.cpp:1149:1: error: 'DSPI1' does not name a type
 DSPI1::DSPI1() : DSPI(_DSPI1_MISO_PIN, _DSPI1_MOSI_PIN, _DSPI1_MISO_IN, _DSPI1_MOSI_OUT)

 ^
/Users/rickanderson/Library/Arduino15/packages/chipKIT/hardware/pic32/1.1.0/libraries/DSPI/DSPI.cpp:1181:1: error: 'DSPI1' has not been declared
 DSPI1::enableInterruptTransfer() {

 ^
/Users/rickanderson/Library/Arduino15/packages/chipKIT/hardware/pic32/1.1.0/libraries/DSPI/DSPI.cpp: In function 'void enableInterruptTransfer()':
/Users/rickanderson/Library/Arduino15/packages/chipKIT/hardware/pic32/1.1.0/libraries/DSPI/DSPI.cpp:1183:11: error: invalid use of 'this' in non-member function
  pdspi1 = this;

           ^
/Users/rickanderson/Library/Arduino15/packages/chipKIT/hardware/pic32/1.1.0/libraries/DSPI/DSPI.cpp:1184:32: error: cannot call member function 'void DSPI::enableInterruptTransfer()' without object
  DSPI::enableInterruptTransfer();

                                ^
/Users/rickanderson/Library/Arduino15/packages/chipKIT/hardware/pic32/1.1.0/libraries/DSPI/DSPI.cpp: At global scope:
/Users/rickanderson/Library/Arduino15/packages/chipKIT/hardware/pic32/1.1.0/libraries/DSPI/DSPI.cpp:1204:1: error: 'DSPI1' has not been declared
 DSPI1::disableInterruptTransfer() {

 ^
/Users/rickanderson/Library/Arduino15/packages/chipKIT/hardware/pic32/1.1.0/libraries/DSPI/DSPI.cpp: In function 'void disableInterruptTransfer()':
/Users/rickanderson/Library/Arduino15/packages/chipKIT/hardware/pic32/1.1.0/libraries/DSPI/DSPI.cpp:1207:33: error: cannot call member function 'void DSPI::disableInterruptTransfer()' without object
  DSPI::disableInterruptTransfer();

                                 ^
exit status 255
Error compiling.

```

**Comment by EmbeddedMan** [comment]
Well, that stinks. I'll work on fixing this.

**Comment by EmbeddedMan** [comment]
Rick, I get zero errors when I use the latest chipKIT-core, with the sketch above, compiled for a FBMini.

**Comment by EmbeddedMan** [comment]
When I compile with release 1.1.0, then I get the errors you are getting. There has been one commit from Keith that fixed some things that is probably the reason master works when 1.1.0 doesn't. 

So I believe this problem is solved with the very latest code in GitHub. Can you test with the latest to see if it fixes for you too?

**Comment by ricklon** [comment]
I will test that. :-)

**Comment by ricklon** [comment]
This works in current master.

**Comment by EmbeddedMan** [comment]
OK, good. I'll close this now, and we can do a new release whenever we feel there's a strong reason to do so (maybe getting this fix out to folks is a good reason?)
